# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 02:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programasradiales',
            name='radios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Radio'),
        ),
    ]
