# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20180104_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programasradiales',
            name='duracion',
            field=models.PositiveSmallIntegerField(default=False, verbose_name='Duración del programa(minutos)'),
        ),
    ]
