# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 19:34
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20180109_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programasradiales',
            name='dias',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('0', 'Domingo')], max_length=40, verbose_name='Selecciona los días'),
        ),
    ]
