# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 20:12
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20180111_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programasradiales',
            name='dias',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miercoles'), ('3', 'Jueves'), ('4', 'Viernes'), ('5', 'Sábado'), ('6', 'Domingo')], max_length=40, verbose_name='Selecciona los días'),
        ),
    ]
